
services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: >
      bash -c "until nc -z db 5432; do echo 'Esperando DB...'; sleep 1; done &&
              PYTHONPATH=. python app/init_db.py &&
              uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge