
services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: fastapi_app
  #   restart: always
  #   volumes:
  #     - ./backend/app:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./backend/app/.env

volumes:
  postgres_data:
